using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Windows.Media;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.Win32;
using Model;
using Repository.PatientPersistance;
using Repository.PeriodPersistance;
using ZdravoHospital.GUI.ManagerUI.DTOs;

namespace ZdravoHospital.Services.Manager
{
    public class DoctorReportService
    {
        #region Fields

        private IPeriodRepository _periodRepository;
        private IPatientRepository _patientRepository;

        private static string path = @"..\..\..\EXPORTPDF\Manager\";

        #endregion

        public DoctorReportService(InjectorDTO injector)
        {
            _periodRepository = injector.PeriodRepository;
            _patientRepository = injector.PatientRepository;
        }

        public ObservableCollection<DoctorReportDTO> CreateReport(Doctor doctor, DateTime start, DateTime end)
        {
            var report = new List<DoctorReportDTO>();

            var periods = _periodRepository.GetValues();

            foreach (var period in periods)
            {
                if (period.DoctorUsername.Equals(doctor.Username) &&
                    ((period.StartTime < start && period.StartTime.AddMinutes(period.Duration) > start) ||
                     (period.StartTime > start && period.StartTime.AddMinutes(period.Duration) < end) ||
                     (period.StartTime < end && period.StartTime.AddMinutes(period.Duration) > end)))
                {
                    report.Add(new DoctorReportDTO()
                    {
                        Date = period.StartTime,
                        PatientName = _patientRepository.GetById(period.PatientUsername).Name,
                        PatientUsername = period.PatientUsername,
                        RoomNumber = period.RoomId,
                        Type = (period.PeriodType == PeriodType.APPOINTMENT) ? "APPOINTMENT" : "OPERATION"
                    });
                }
            }
            
            return new ObservableCollection<DoctorReportDTO>(report);
        }

        public void GeneratePDF(Doctor doctor, DateTime start, DateTime end, List<DoctorReportDTO> doctorReport)
        {
            Document document = new Document(PageSize.A4);

            var currentPath = path + doctor.Name + "-" 
                              + start.Day + "_" + start.Month + "_" + start.Year + "-" 
                              + end.Day + "_" + end.Month + "_" + end.Year + "-" 
                              + Guid.NewGuid() + ".pdf";

            FileStream outputStream = new FileStream(currentPath, FileMode.Create);

            using (outputStream)
            {
                PdfWriter.GetInstance(document, outputStream);
                document.Open();

                Paragraph intro = new Paragraph();
                intro.Add("Autogenerated report for Doctor : \n");
                intro.Add(doctor.Format() + "\n");
                document.Add(intro);

                Paragraph split = new Paragraph("\n--------- REPORT ---------");
                document.Add(split);

                Paragraph report = new Paragraph();
                foreach (var docrep in doctorReport)
                {
                    report.Add(docrep.Format() + "\n\n");
                }

                document.Add(report);

                document.Close();
            }
        }
    }
}
